colors:
  body: none
  date: BLUE
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: ~/Documents/notes/Aktuelles.txt
  deve:
    encrypt: false
    journal: /lhome/dkadiog/Documents/notes/DEVE/aktuell.txt
    template: /lhome/dkadiog/Documents/notes/.notes/deve.txt
  kar:
    encrypt: false
    journal: /lhome/dkadiog/Documents/notes/KAR/atkuell.txt
    template: /lhome/dkadiog/Documents/notes/.notes/kar.txt
  learn:
    encrypt: false
    journal: /lhome/dkadiog/Documents/notes/learn/aktuell.txt
    template: /lhome/dkadiog/Documents/notes/.notes/template.txt
  paacs:
    encrypt: false
    journal: /lhome/dkadiog/Documents/notes/paacs/aktuell.txt
    template: /lhome/dkadiog/Documents/notes/.notes/paacs.txt
  tdp:
    encrypt: false
    journal: /lhome/dkadiog/Documents/notes/TDP/aktuell.txt
    template: /lhome/dkadiog/Documents/notes/.notes/tdp.txt
  wv:
    encrypt: false
    journal: /lhome/dkadiog/Documents/notes/WebVis/aktuell.txt
    template: /lhome/dkadiog/Documents/notes/.notes/wv.txt
linewrap: 79
tagsymbols: '@'
template: ~/Documents/notes/.notes/template.txt
timeformat: '%Y-%m-%d %H:%M'
version: v4.1
